apiVersion: v1
kind: Namespace
metadata:
  name: portfolio
  labels:
    name: portfolio
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: portfolio
  labels:
    app: portfolio
spec:
  ports:
    - name: portfolio-http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: portfolio-jnlp
      port: 50000
      protocol: TCP
      targetPort: 50000
  selector:
    app: portfolio
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: portfolio
  namespace: portfolio
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`jonatanlindstrom.se`)
      kind: Rule
      services:
        - name: portfolio
          port: 80
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: jenkins-admin-token
#   namespace: jenkins
#   annotations:
#     kubernetes.io/service-account.name: jenkins-admin
# type: kubernetes.io/service-account-token
